### ISSUE TITLE
consistently return fcsFileId from getGates

### ISSUE THREAD

**Issue by pfgherardini** [primitybio/cellengine-r-toolkit#9]
Right now getGates does not return the fcsFileId column if a gate is tailored but has not actually being tailored yet. This makes working with the return value more complicated. It'd be best to have the fcsFileId column to always be there

**Comment by zbjornson** [comment]
@pfgherardini FYI the referenced commit will make that column always present, at least with the value `NA`, in R. In the near future we'll probably make that field actually `null` coming from our servers. There are already some scenarios when a gate will have `tailoredPerFile: false, fcsFileId: null` instead of `tailoredPerFile: false, fcsFileId: <undefined>`.
